Add Editor Integration section to README
lpil/exfmt pull request #35
Opened 2017-07-25 01:54 UTC by rgreenjr

## Description

This pull request adds an **Editor Integration** section to the README. It describes the new Atom `exfmt-atom` plugin and will hopefully include more integrations soon.

## Checklist

- [x] The change has been discussed in a GitHub issue.
- [] There are tests for the new functionality.
- [x] I agree to adhere to the code of conduct.

2017-07-25 19:33 UTC, jfornoff requested changes

2017-07-25 19:33 UTC, jfornoff commented on README.md
> +- [Editor Integration](#editorintegration)
I think you need a dash in the anchor (`editor-integration`) to work with the heading below.
You can check it working in the `Files changed` tab and hitting the `View` button on the top right! ;-)

2017-07-25 20:47 UTC, rgreenjr commented on README.md
> +- [Editor Integration](#editorintegration)
Thanks for the heads-up.

2017-07-26 11:16 UTC, lpil commented on README.md
> +- [Editor Integration](#editor-integration)
Could you add a sub-item here please? :)

```
- [Editor Integration](#editor-integration)
  - [Atom](#atom)
```

2017-07-26 13:36 UTC, rgreenjr commented on README.md
> +- [Editor Integration](#editor-integration)
Absolutely.

2017-07-26 14:55 UTC, lpil commented
Thank you @rgreenjr ! :D

2017-07-26 14:55 UTC, merged